services:
  - type: web
    name: telegram-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker app:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
